### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by pepinu** [JaeYeonKang/STVUN-Pytorch#2]
Hey, I've gone through the tutorial in the README.md, but was not able to run the demo.py:

> Traceback (most recent call last):
>   File "demo.py", line 10, in <module>
>     from networks.correlation_package_pytorch.correlation import Correlation
>   File "/content/STVUN-Pytorch/networks/correlation_package_pytorch/correlation.py", line 4, in <module>
>     import correlation_cuda
> ImportError: /usr/local/lib/python3.6/dist-packages/correlation_cuda-0.0.0-py3.6-linux-x86_64.egg/correlation_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

Installed dependencies:
CUDA 10.2
Pytorch 1.6

After installing with:
`python setup.py install`

> running install
> running bdist_egg
> running egg_info
> writing correlation_cuda.egg-info/PKG-INFO
> writing dependency_links to correlation_cuda.egg-info/dependency_links.txt
> writing top-level names to correlation_cuda.egg-info/top_level.txt
> /usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py:335: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
>   warnings.warn(msg.format('we could not find ninja.'))
> writing manifest file 'correlation_cuda.egg-info/SOURCES.txt'
> installing library code to build/bdist.linux-x86_64/egg
> running install_lib
> running build_ext
> creating build/bdist.linux-x86_64
> creating build/bdist.linux-x86_64/egg
> copying build/lib.linux-x86_64-3.6/correlation_cuda.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
> creating stub loader for correlation_cuda.cpython-36m-x86_64-linux-gnu.so
> byte-compiling build/bdist.linux-x86_64/egg/correlation_cuda.py to correlation_cuda.cpython-36.pyc
> creating build/bdist.linux-x86_64/egg/EGG-INFO
> copying correlation_cuda.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying correlation_cuda.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying correlation_cuda.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying correlation_cuda.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
> zip_safe flag not set; analyzing archive contents...
> __pycache__.correlation_cuda.cpython-36: module references __file__
> creating 'dist/correlation_cuda-0.0.0-py3.6-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
> removing 'build/bdist.linux-x86_64/egg' (and everything under it)
> Processing correlation_cuda-0.0.0-py3.6-linux-x86_64.egg
> creating /usr/local/lib/python3.6/dist-packages/correlation_cuda-0.0.0-py3.6-linux-x86_64.egg
> Extracting correlation_cuda-0.0.0-py3.6-linux-x86_64.egg to /usr/local/lib/python3.6/dist-packages
> Adding correlation-cuda 0.0.0 to easy-install.pth file
> 
> Installed /usr/local/lib/python3.6/dist-packages/correlation_cuda-0.0.0-py3.6-linux-x86_64.egg
> Processing dependencies for correlation-cuda==0.0.0
> Finished processing dependencies for correlation-cuda==0.0.0

Any ideas? The 0.0.0 version looks weird

**Comment by JaeYeonKang** [comment]
Sorry for the confusion.
Use ./build.sh instead of python setup.py install.
If it still occur some error, please use pytorch 1.2 version.
